### ISSUE TITLE
GAMES_005B Tic-Tac-Toe: Collecting user points

### ISSUE THREAD

**Issue by brovic09** [sw20-tug/SWT-Morning-2#18]
Users should earn and lose points for games in Tic-Tac-Toe. They are tracked in the global user score.

**Acceptance Criteria:**

- User gets one point for every Tic-Tac-Toe game he wins
- User loses two points for every game he loses

**Comment by dermyGIT** [comment]
Use application context for the `ScoreTracker` class.
