### ISSUE TITLE
GAMES_000C Feedback Sprint 1

### ISSUE THREAD

**Issue by glocka** [sw20-tug/SWT-Morning-2#29]
Fix the mentioned issues in the report (see attached file below)

**Acceptance Criteria:**
- [x] add details to README (used technology, set up the project)
- [x] consistent use of the identifier (GAME_000A vs. GAME-013)
- [x] check local git commit name and email address
- [x] use linter in Gitlab Actions
- [x] check if all Issues which are marked as Done are also closed

[swt-morning-2.pdf](https://github.com/sw20-tug/SWT-Morning-2/files/4438512/swt-morning-2.pdf)

**Comment by glocka** [comment]
[swt-morning-2.pdf](https://github.com/sw20-tug/SWT-Morning-2/files/4438438/swt-morning-2.pdf)

**Comment by Karatekuh** [comment]
Everything corrected.
