### ISSUE TITLE
GAMES_000G Hint tutors for possible improvements

### ISSUE THREAD

**Issue by glocka** [sw20-tug/SWT-Morning-2#44]
Some of the rules are counterintuitive.

TODO:
- [ ] In Sprint 3 report add a short description of these issues (does not make sense in my opinion)
- [ ] not splitting up issue on the way because of existing commit messages contain issue name already (was answered in slack. "Think before you start working")
- [ ] no link from commit to issue via the short commit identifier (valid concern)

**Comment by dermyGIT** [comment]
I think this would rather fit into the evaluation of the course, rather than the report of a sprint. People will forget about what we tell them during the report. They don't expect course feedback there.

**Comment by dermyGIT** [comment]
Course evaluation is open already, provide feedback there individually.
