### ISSUE TITLE
GAMES_005 Tic-Tac-Toe: Collecting user points

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/SWT-Morning-2#5]
As a user I want to see how I am performing to challenge myself.

**Acceptance criteria:**
- User gets one point for every Tic-Tac-Toe game he wins
- User loses two points for every game he loses
- Points are displayed on the main screen
- User can later also get points for other games

**Comment by brovic09** [comment]
Split into #17 and #18

**Comment by brovic09** [comment]
The gain of points is handled in their respective game issues. See #11 and #6.
Main screen is handled in #28.
